2014-07-30 00:10:08.940 [error] emulator Error in process <0.3798.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,{badmatch,[<<33 bytes>>]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-07-30 00:10:08.940 [error] <0.3792.0>@cf_exe:3c69c813-9242-1232-b7a5-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,{badmatch,[<<"00918146818513test.viithiisys.com">>]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-07-30 00:22:55.225 [error] emulator Error in process <0.1810.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-07-30 00:22:55.225 [error] <0.1804.0>@cf_exe:0594bbdb-9244-1232-b7a5-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-07-30 00:41:08.948 [error] emulator Error in process <0.5309.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-07-30 00:41:08.948 [error] <0.5303.0>@cf_exe:91a7ecb0-9246-1232-b7a5-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-07-30 00:43:01.938 [error] emulator Error in process <0.5741.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-07-30 00:43:01.938 [error] <0.5735.0>@cf_exe:d5025dd1-9246-1232-b7a5-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-07-30 00:49:39.100 [error] emulator Error in process <0.7664.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-07-30 00:49:39.100 [error] <0.7658.0>@cf_exe:c1a3d125-9247-1232-b7a5-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-07-30 00:57:51.077 [error] emulator Error in process <0.1807.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-07-30 00:57:51.078 [error] <0.1801.0>@cf_exe:e6e4de35-9248-1232-b7a5-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-07-30 01:04:04.239 [error] emulator Error in process <0.1836.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-07-30 01:04:04.239 [error] <0.1830.0>@cf_exe:c5383067-9249-1232-b7a5-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-07-30 12:50:51.712 [error] <0.870.0> Supervisor {<0.870.0>,ecallmgr_fs_event_stream_sup} had child 'sofia::register' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'sofia::register') at <0.876.0> exit with reason normal in context child_terminated
2014-07-30 12:50:51.713 [error] <0.870.0> Supervisor {<0.870.0>,ecallmgr_fs_event_stream_sup} had child 'whistle::noop' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'whistle::noop') at <0.871.0> exit with reason normal in context child_terminated
2014-07-30 12:50:51.714 [error] <0.870.0> Supervisor {<0.870.0>,ecallmgr_fs_event_stream_sup} had child 'sofia::replaced' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'sofia::replaced') at <0.875.0> exit with reason normal in context child_terminated
2014-07-30 12:50:51.715 [error] <0.870.0> Supervisor {<0.870.0>,ecallmgr_fs_event_stream_sup} had child 'sofia::transferor' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'sofia::transferor') at <0.873.0> exit with reason normal in context child_terminated
2014-07-30 12:50:51.716 [error] <0.870.0> Supervisor {<0.870.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_ANSWER' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_ANSWER', undefined) at <0.889.0> exit with reason normal in context child_terminated
2014-07-30 12:50:51.717 [error] <0.870.0> Supervisor {<0.870.0>,ecallmgr_fs_event_stream_sup} had child 'channel_move::move_released' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'channel_move::move_released') at <0.884.0> exit with reason normal in context child_terminated
2014-07-30 12:50:51.717 [error] <0.870.0> Supervisor {<0.870.0>,ecallmgr_fs_event_stream_sup} had child 'channel_move::move_released' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'channel_move::move_released') at <0.884.0> exit with reason reached_max_restart_intensity in context shutdown
2014-07-30 12:50:51.719 [error] <0.835.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_event_stream_sup' started with ecallmgr_fs_event_stream_sup:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.870.0> exit with reason shutdown in context child_terminated
2014-07-30 12:50:51.889 [critical] <0.6229.2>@ecallmgr_fs_nodes:536 recieved node down notice for freeswitch@kazoo.viithiisys.com
2014-07-30 12:50:51.891 [error] <0.835.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_authn' started with ecallmgr_fs_authn:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.843.0> exit with reason noconnection in context child_terminated
2014-07-30 12:50:51.895 [error] <0.835.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_channel' started with ecallmgr_fs_channel:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.845.0> exit with reason noconnection in context child_terminated
2014-07-30 12:50:51.897 [error] <0.835.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_config' started with ecallmgr_fs_config:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.846.0> exit with reason noconnection in context child_terminated
2014-07-30 12:50:51.898 [error] <0.835.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_route' started with ecallmgr_fs_route:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.844.0> exit with reason noconnection in context child_terminated
2014-07-30 12:50:52.016 [error] <0.184.0> gen_server <0.184.0> terminated with reason: no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241
2014-07-30 12:50:52.016 [error] <0.184.0> CRASH REPORT Process <0.184.0> with 0 neighbours exited with reason: no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241 in gen_server:terminate/6 line 747
2014-07-30 12:50:52.017 [error] <0.178.0> Supervisor wh_couch_connection_sup had child wh_couch_connection started with wh_couch_connection:start_link({wh_couch_connection,2,"127.0.0.1",15986,[],[],false,false,true,{server,undefined,undefined,undefined,...}}) at <0.184.0> exit with reason no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241 in context child_terminated
2014-07-30 12:50:52.018 [error] <0.178.0> Supervisor wh_couch_connection_sup had child wh_couch_connection started with wh_couch_connection:start_link({wh_couch_connection,2,"127.0.0.1",15986,[],[],false,false,true,{server,undefined,undefined,undefined,...}}) at <0.184.0> exit with reason reached_max_restart_intensity in context shutdown
2014-07-30 12:50:52.018 [error] <0.171.0> Supervisor whistle_couch_sup had child wh_couch_connection_sup started with wh_couch_connection_sup:start_link() at <0.178.0> exit with reason shutdown in context child_terminated
2014-07-30 12:51:04.369 [error] <0.108.0> Connection (<0.108.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-07-30 12:51:04.378 [critical] <0.105.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: closing
2014-07-30 12:51:04.470 [error] <0.110.0> Connection (<0.110.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-07-30 12:51:04.484 [error] <0.110.0> gen_server <0.110.0> terminated with reason: socket_closed_unexpectedly
2014-07-30 12:51:04.484 [error] <0.110.0> CRASH REPORT Process <0.110.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/6 line 747
2014-07-30 12:51:04.488 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason socket_closed_unexpectedly in context child_terminated
2014-07-30 12:51:04.493 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason reached_max_restart_intensity in context shutdown
2014-07-30 12:51:04.497 [error] <0.107.0> gen_server <0.107.0> terminated with reason: {socket_closed_unexpectedly,{gen_server,call,[<0.110.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},infinity]}}
2014-07-30 12:51:04.498 [error] <0.107.0> CRASH REPORT Process <0.107.0> with 0 neighbours exited with reason: {socket_closed_unexpectedly,{gen_server,call,[<0.110.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},infinity]}} in gen_server:terminate/6 line 747
2014-07-30 12:51:04.500 [error] <0.101.0> Supervisor wh_amqp_connection_sup had child wh_amqp_connection started with wh_amqp_connection:start_link({wh_amqp_connection,<<"amqp://guest:guest@127.0.0.1:5672">>,{amqp_params_network,<<"guest">>,<<"gu...">>,...},...}) at <0.107.0> exit with reason {socket_closed_unexpectedly,{gen_server,call,[<0.110.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},infinity]}} in context child_terminated
2014-07-31 09:58:24.102 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'spandsp::txfaxnegociateresult' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'spandsp::txfaxnegociateresult') at <0.880.0> exit with reason normal in context child_terminated
2014-07-31 09:58:24.103 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'channel_move::move_released' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'channel_move::move_released') at <0.882.0> exit with reason normal in context child_terminated
2014-07-31 09:58:24.103 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'channel_move::move_complete' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'channel_move::move_complete') at <0.883.0> exit with reason normal in context child_terminated
2014-07-31 09:58:24.104 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'spandsp::rxfaxpageresult' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'spandsp::rxfaxpageresult') at <0.879.0> exit with reason normal in context child_terminated
2014-07-31 09:58:24.112 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_CREATE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_CREATE', undefined) at <0.884.0> exit with reason normal in context child_terminated
2014-07-31 09:58:24.119 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'whistle::noop' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'whistle::noop') at <0.869.0> exit with reason normal in context child_terminated
2014-07-31 09:58:24.119 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'whistle::noop' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'whistle::noop') at <0.869.0> exit with reason reached_max_restart_intensity in context shutdown
2014-07-31 09:58:24.119 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CALL_SECURE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CALL_SECURE', undefined) at <0.898.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.119 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_DATA' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_DATA', undefined) at <0.897.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.119 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_EXECUTE_COMPLETE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_EXECUTE_COMPLETE', undefined) at <0.896.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.119 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_EXECUTE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_EXECUTE', undefined) at <0.895.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.120 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_UNBRIDGE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_UNBRIDGE', undefined) at <0.894.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.120 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_BRIDGE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_BRIDGE', undefined) at <0.893.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.120 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'RECORD_STOP' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'RECORD_STOP', undefined) at <0.892.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.120 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'RECORD_START' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'RECORD_START', undefined) at <0.891.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.121 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'DTMF' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'DTMF', undefined) at <0.890.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.121 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'DETECTED_TONE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'DETECTED_TONE', undefined) at <0.889.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.121 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CALL_UPDATE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CALL_UPDATE', undefined) at <0.888.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.121 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_ANSWER' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_ANSWER', undefined) at <0.887.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.122 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_DESTROY' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_DESTROY', undefined) at <0.886.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.122 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_PROGRESS_MEDIA' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_PROGRESS_MEDIA', undefined) at <0.885.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.122 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'spandsp::rxfaxnegociateresult' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'spandsp::rxfaxnegociateresult') at <0.881.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.122 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'spandsp::txfaxpageresult' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'spandsp::txfaxpageresult') at <0.878.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.122 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'spandsp::rxfaxresult' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'spandsp::rxfaxresult') at <0.877.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.123 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'spandsp::txfaxresult' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'spandsp::txfaxresult') at <0.876.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.123 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'conference::maintenance' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'conference::maintenance') at <0.875.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.123 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'sofia::register' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'sofia::register') at <0.874.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.123 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'sofia::replaced' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'sofia::replaced') at <0.873.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.123 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'sofia::transferee' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'sofia::transferee') at <0.872.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.123 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'sofia::transferor' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'sofia::transferor') at <0.871.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.124 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'whistle::masquerade' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'whistle::masquerade') at <0.870.0> exit with reason normal in context shutdown_error
2014-07-31 09:58:24.124 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_event_stream_sup' started with ecallmgr_fs_event_stream_sup:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.867.0> exit with reason shutdown in context child_terminated
2014-07-31 09:58:24.408 [critical] <0.8318.0>@ecallmgr_fs_nodes:536 recieved node down notice for freeswitch@kazoo.viithiisys.com
2014-07-31 09:58:24.409 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_authn' started with ecallmgr_fs_authn:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.840.0> exit with reason noconnection in context child_terminated
2014-07-31 09:58:24.409 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_channel' started with ecallmgr_fs_channel:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.842.0> exit with reason noconnection in context child_terminated
2014-07-31 09:58:24.411 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_config' started with ecallmgr_fs_config:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.843.0> exit with reason noconnection in context child_terminated
2014-07-31 09:58:24.411 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_route' started with ecallmgr_fs_route:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.841.0> exit with reason noconnection in context child_terminated
2014-07-31 09:58:26.728 [error] <0.184.0> gen_server <0.184.0> terminated with reason: no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241
2014-07-31 09:58:26.728 [error] <0.184.0> CRASH REPORT Process <0.184.0> with 0 neighbours exited with reason: no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241 in gen_server:terminate/6 line 747
2014-07-31 09:58:26.729 [error] <0.178.0> Supervisor wh_couch_connection_sup had child wh_couch_connection started with wh_couch_connection:start_link({wh_couch_connection,2,"127.0.0.1",15986,[],[],false,false,true,{server,undefined,undefined,undefined,...}}) at <0.184.0> exit with reason no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241 in context child_terminated
2014-07-31 09:58:26.730 [error] <0.178.0> Supervisor wh_couch_connection_sup had child wh_couch_connection started with wh_couch_connection:start_link({wh_couch_connection,2,"127.0.0.1",15986,[],[],false,false,true,{server,undefined,undefined,undefined,...}}) at <0.184.0> exit with reason reached_max_restart_intensity in context shutdown
2014-07-31 09:58:26.730 [error] <0.171.0> Supervisor whistle_couch_sup had child wh_couch_connection_sup started with wh_couch_connection_sup:start_link() at <0.178.0> exit with reason shutdown in context child_terminated
2014-07-31 09:58:34.191 [error] <0.108.0> Connection (<0.108.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-07-31 09:58:34.206 [error] <0.108.0> gen_server <0.108.0> terminated with reason: socket_closed_unexpectedly
2014-07-31 09:58:34.206 [error] <0.108.0> CRASH REPORT Process <0.108.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/6 line 747
2014-07-31 09:58:34.207 [critical] <0.105.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: not_connected
2014-07-31 09:58:34.209 [error] <0.106.0> Supervisor {<0.106.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.107.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.108.0> exit with reason socket_closed_unexpectedly in context child_terminated
2014-07-31 09:58:34.213 [error] <0.106.0> Supervisor {<0.106.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.107.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.108.0> exit with reason reached_max_restart_intensity in context shutdown
2014-07-31 09:58:34.425 [error] <0.110.0> Connection (<0.110.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-07-31 09:58:34.438 [error] <0.110.0> gen_server <0.110.0> terminated with reason: socket_closed_unexpectedly
2014-07-31 09:58:34.439 [error] <0.110.0> CRASH REPORT Process <0.110.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/6 line 747
2014-07-31 09:58:34.451 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason socket_closed_unexpectedly in context child_terminated
2014-07-31 09:58:34.455 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason reached_max_restart_intensity in context shutdown
2014-07-31 09:58:34.457 [error] <0.107.0> gen_server <0.107.0> terminated with reason: {socket_closed_unexpectedly,{gen_server,call,[<0.110.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},infinity]}}
2014-07-31 09:58:34.461 [error] <0.107.0> CRASH REPORT Process <0.107.0> with 0 neighbours exited with reason: {socket_closed_unexpectedly,{gen_server,call,[<0.110.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},infinity]}} in gen_server:terminate/6 line 747
2014-07-31 09:58:34.463 [error] <0.101.0> Supervisor wh_amqp_connection_sup had child wh_amqp_connection started with wh_amqp_connection:start_link({wh_amqp_connection,<<"amqp://guest:guest@127.0.0.1:5672">>,{amqp_params_network,<<"guest">>,<<"gu...">>,...},...}) at <0.107.0> exit with reason {socket_closed_unexpectedly,{gen_server,call,[<0.110.0>,{command,{open_channel,none,{amqp_selective_consumer,[]}}},infinity]}} in context child_terminated
2014-08-07 00:07:38.513 [error] <0.110.0> Connection (<0.110.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-07 00:07:38.517 [error] <0.108.0> Connection (<0.108.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-07 00:07:38.678 [critical] <0.105.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: not_connected
2014-08-07 00:07:38.677 [critical] <0.107.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: not_connected
2014-08-07 00:07:46.027 [error] <0.389.0> gen_server wh_gen_changes_offnet terminated with reason: connection_closed
2014-08-07 00:07:46.027 [error] <0.389.0> CRASH REPORT Process wh_gen_changes_offnet with 0 neighbours exited with reason: connection_closed in gen_server:terminate/6 line 747
2014-08-07 00:07:46.030 [error] <0.189.0> Supervisor wh_change_handler_sup had child wh_change_handler started with wh_change_handler:start_link({db,{server,"127.0.0.1",15984,[],[{max_sessions,512},{max_pipeline_size,10},{connect_timeout,500}]},...}, []) at <0.389.0> exit with reason connection_closed in context child_terminated
2014-08-07 00:07:46.030 [error] <0.398.0> gen_server wh_gen_changes_system_config terminated with reason: connection_closed
2014-08-07 00:07:46.031 [error] <0.398.0> CRASH REPORT Process wh_gen_changes_system_config with 0 neighbours exited with reason: connection_closed in gen_server:terminate/6 line 747
2014-08-07 00:07:46.031 [error] <0.189.0> Supervisor wh_change_handler_sup had child wh_change_handler started with wh_change_handler:start_link({db,{server,"127.0.0.1",15984,[],[{max_sessions,512},{max_pipeline_size,10},{connect_timeout,500}]},...}, []) at <0.398.0> exit with reason connection_closed in context child_terminated
2014-08-07 05:13:07.463 [error] emulator Error in process <0.23686.1> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 05:13:07.463 [error] <0.23680.1>@cf_exe:e3701af9-98b5-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 05:18:02.045 [error] emulator Error in process <0.1797.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 05:18:02.045 [error] <0.1791.0>@cf_exe:9340501f-98b6-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 05:58:33.905 [error] emulator Error in process <0.8472.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 05:58:33.905 [error] <0.8466.0>@cf_exe:3cd5f7d6-98bc-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 05:59:29.035 [error] emulator Error in process <0.1799.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 05:59:29.036 [error] <0.1793.0>@cf_exe:5d9e5800-98bc-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 06:07:12.129 [error] emulator Error in process <0.3481.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 06:07:12.129 [error] <0.3474.0>@cf_exe:71966e5e-98bd-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 08:26:57.940 [error] emulator Error in process <0.3026.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 08:26:57.940 [error] <0.3019.0>@cf_exe:f808983a-98d0-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 08:43:54.095 [error] emulator Error in process <0.1827.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,{badmatch,[]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 08:43:54.095 [error] <0.1821.0>@cf_exe:559dee0e-98d3-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,{badmatch,[]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 08:45:58.050 [error] emulator Error in process <0.1787.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,{badmatch,[]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 08:45:58.050 [error] <0.1781.0>@cf_exe:9f8696ad-98d3-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,{badmatch,[]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 09:11:39.052 [error] emulator Error in process <0.1803.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,{badmatch,[]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 09:11:39.052 [error] <0.1797.0>@cf_exe:36089fa9-98d7-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,{badmatch,[]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 09:12:24.288 [error] emulator Error in process <0.1783.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,{badmatch,[]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-07 09:12:24.288 [error] <0.1777.0>@cf_exe:50daee57-98d7-1232-b6b2-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,{badmatch,[]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-07 09:39:07.998 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'sofia::transferee' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'sofia::transferee') at <0.871.0> exit with reason normal in context child_terminated
2014-08-07 09:39:08.007 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'spandsp::rxfaxnegociateresult' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'spandsp::rxfaxnegociateresult') at <0.880.0> exit with reason normal in context child_terminated
2014-08-07 09:39:08.008 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'RECORD_START' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'RECORD_START', undefined) at <0.890.0> exit with reason normal in context child_terminated
2014-08-07 09:39:08.008 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_UNBRIDGE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_UNBRIDGE', undefined) at <0.893.0> exit with reason normal in context child_terminated
2014-08-07 09:39:08.009 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CALL_SECURE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CALL_SECURE', undefined) at <0.897.0> exit with reason normal in context child_terminated
2014-08-07 09:39:08.027 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'RECORD_STOP' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'RECORD_STOP', undefined) at <0.891.0> exit with reason normal in context child_terminated
2014-08-07 09:39:08.028 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'RECORD_STOP' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'RECORD_STOP', undefined) at <0.891.0> exit with reason reached_max_restart_intensity in context shutdown
2014-08-07 09:39:08.029 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_event_stream_sup' started with ecallmgr_fs_event_stream_sup:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.867.0> exit with reason shutdown in context child_terminated
2014-08-07 09:39:08.455 [critical] <0.18297.1>@ecallmgr_fs_nodes:536 recieved node down notice for freeswitch@kazoo.viithiisys.com
2014-08-07 09:39:08.458 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_authn' started with ecallmgr_fs_authn:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.840.0> exit with reason noconnection in context child_terminated
2014-08-07 09:39:08.460 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_channel' started with ecallmgr_fs_channel:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.842.0> exit with reason noconnection in context child_terminated
2014-08-07 09:39:08.461 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_config' started with ecallmgr_fs_config:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.843.0> exit with reason noconnection in context child_terminated
2014-08-07 09:39:08.462 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_route' started with ecallmgr_fs_route:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.841.0> exit with reason noconnection in context child_terminated
2014-08-07 09:39:12.515 [error] <0.184.0> gen_server <0.184.0> terminated with reason: no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241
2014-08-07 09:39:12.515 [error] <0.184.0> CRASH REPORT Process <0.184.0> with 0 neighbours exited with reason: no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241 in gen_server:terminate/6 line 747
2014-08-07 09:39:12.515 [error] <0.178.0> Supervisor wh_couch_connection_sup had child wh_couch_connection started with wh_couch_connection:start_link({wh_couch_connection,2,"127.0.0.1",15986,[],[],false,false,true,{server,undefined,undefined,undefined,...}}) at <0.184.0> exit with reason no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241 in context child_terminated
2014-08-07 09:39:12.516 [error] <0.178.0> Supervisor wh_couch_connection_sup had child wh_couch_connection started with wh_couch_connection:start_link({wh_couch_connection,2,"127.0.0.1",15986,[],[],false,false,true,{server,undefined,undefined,undefined,...}}) at <0.184.0> exit with reason reached_max_restart_intensity in context shutdown
2014-08-07 09:39:12.516 [error] <0.171.0> Supervisor whistle_couch_sup had child wh_couch_connection_sup started with wh_couch_connection_sup:start_link() at <0.178.0> exit with reason shutdown in context child_terminated
2014-08-07 09:39:18.854 [error] <0.108.0> Connection (<0.108.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-07 09:39:18.848 [error] <0.110.0> Connection (<0.110.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-07 09:39:18.861 [critical] <0.105.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: closing
2014-08-07 09:39:18.869 [critical] <0.107.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: closing
2014-08-07 09:39:18.869 [error] <0.110.0> gen_server <0.110.0> terminated with reason: socket_closed_unexpectedly
2014-08-07 09:39:18.869 [error] <0.110.0> CRASH REPORT Process <0.110.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/6 line 747
2014-08-07 09:39:18.879 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason socket_closed_unexpectedly in context child_terminated
2014-08-07 09:39:18.883 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason reached_max_restart_intensity in context shutdown
2014-08-08 00:14:09.986 [error] <0.110.0> Connection (<0.110.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-08 00:14:09.989 [error] <0.108.0> Connection (<0.108.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-08 00:14:10.080 [critical] <0.107.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: not_connected
2014-08-08 00:14:10.077 [critical] <0.105.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: not_connected
2014-08-08 00:14:17.335 [error] <0.389.0> gen_server wh_gen_changes_offnet terminated with reason: connection_closed
2014-08-08 00:14:17.335 [error] <0.389.0> CRASH REPORT Process wh_gen_changes_offnet with 0 neighbours exited with reason: connection_closed in gen_server:terminate/6 line 747
2014-08-08 00:14:17.338 [error] <0.403.0> gen_server wh_gen_changes_system_config terminated with reason: connection_closed
2014-08-08 00:14:17.338 [error] <0.403.0> CRASH REPORT Process wh_gen_changes_system_config with 0 neighbours exited with reason: connection_closed in gen_server:terminate/6 line 747
2014-08-08 00:14:17.339 [error] <0.189.0> Supervisor wh_change_handler_sup had child wh_change_handler started with wh_change_handler:start_link({db,{server,"127.0.0.1",15984,[],[{max_sessions,512},{max_pipeline_size,10},{connect_timeout,500}]},...}, []) at <0.389.0> exit with reason connection_closed in context child_terminated
2014-08-08 00:14:17.340 [error] <0.189.0> Supervisor wh_change_handler_sup had child wh_change_handler started with wh_change_handler:start_link({db,{server,"127.0.0.1",15984,[],[{max_sessions,512},{max_pipeline_size,10},{connect_timeout,500}]},...}, []) at <0.403.0> exit with reason connection_closed in context child_terminated
2014-08-08 02:42:45.048 [error] emulator Error in process <0.2478.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,{case_clause,["false"]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-08 02:42:45.048 [error] <0.2472.0>@cf_exe:0c0819e1-996a-1232-18a9-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,{case_clause,["false"]}},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-08 04:22:55.951 [error] emulator Error in process <0.12514.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-08 04:22:55.951 [error] <0.12508.0>@cf_exe:0a4563c5-9978-1232-18a9-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-08 05:35:01.909 [error] emulator Error in process <0.2160.0> on node 'whistle_apps@kazoo.viithiisys.com' with exit value: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}


2014-08-08 05:35:01.909 [error] <0.2153.0>@cf_exe:1d5d00e4-9982-1232-18a9-f04da2bd5b56:431 action cf_automatic_cid died unexpectedly: {{nocatch,badarg},[{cf_exe,'-spawn_cf_module/3-fun-1-',4,[{file,"src/cf_exe.erl"},{line,622}]}]}
2014-08-08 05:37:17.979 [error] <0.110.0> Connection (<0.110.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-08 05:37:17.993 [error] <0.108.0> Connection (<0.108.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-08 05:37:17.999 [critical] <0.105.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: closing
2014-08-08 05:37:17.988 [critical] <0.107.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: closing
2014-08-08 05:37:18.017 [error] <0.110.0> gen_server <0.110.0> terminated with reason: socket_closed_unexpectedly
2014-08-08 05:37:18.018 [error] <0.110.0> CRASH REPORT Process <0.110.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/6 line 747
2014-08-08 05:37:18.022 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason socket_closed_unexpectedly in context child_terminated
2014-08-08 05:37:18.023 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason reached_max_restart_intensity in context shutdown
2014-08-08 05:37:24.306 [error] <0.922.0> gen_server wh_gen_changes_system_config terminated with reason: connection_closed
2014-08-08 05:37:24.306 [error] <0.922.0> CRASH REPORT Process wh_gen_changes_system_config with 0 neighbours exited with reason: connection_closed in gen_server:terminate/6 line 747
2014-08-08 05:37:24.306 [error] <0.908.0> gen_server wh_gen_changes_offnet terminated with reason: connection_closed
2014-08-08 05:37:24.306 [error] <0.908.0> CRASH REPORT Process wh_gen_changes_offnet with 0 neighbours exited with reason: connection_closed in gen_server:terminate/6 line 747
2014-08-08 05:37:24.307 [error] <0.180.0> Supervisor wh_change_handler_sup had child wh_change_handler started with wh_change_handler:start_link({db,{server,"127.0.0.1",15984,[],[{max_sessions,512},{max_pipeline_size,10},{connect_timeout,500}]},...}, []) at <0.922.0> exit with reason connection_closed in context child_terminated
2014-08-08 05:37:24.307 [error] <0.180.0> Supervisor wh_change_handler_sup had child wh_change_handler started with wh_change_handler:start_link({db,{server,"127.0.0.1",15984,[],[{max_sessions,512},{max_pipeline_size,10},{connect_timeout,500}]},...}, []) at <0.908.0> exit with reason connection_closed in context child_terminated
2014-08-08 09:10:57.044 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_DESTROY' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_DESTROY', undefined) at <0.885.0> exit with reason normal in context child_terminated
2014-08-08 09:10:57.051 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'spandsp::rxfaxresult' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'spandsp::rxfaxresult') at <0.876.0> exit with reason normal in context child_terminated
2014-08-08 09:10:57.176 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'spandsp::txfaxresult' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'spandsp::txfaxresult') at <0.875.0> exit with reason normal in context child_terminated
2014-08-08 09:10:57.179 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'CHANNEL_CREATE' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CHANNEL_CREATE', undefined) at <0.883.0> exit with reason normal in context child_terminated
2014-08-08 09:10:57.199 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'sofia::replaced' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'CUSTOM', 'sofia::replaced') at <0.872.0> exit with reason normal in context child_terminated
2014-08-08 09:10:57.201 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'DTMF' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'DTMF', undefined) at <0.889.0> exit with reason normal in context child_terminated
2014-08-08 09:10:57.201 [error] <0.867.0> Supervisor {<0.867.0>,ecallmgr_fs_event_stream_sup} had child 'DTMF' started with ecallmgr_fs_event_stream:start_link('freeswitch@kazoo.viithiisys.com', 'DTMF', undefined) at <0.889.0> exit with reason reached_max_restart_intensity in context shutdown
2014-08-08 09:10:57.206 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_event_stream_sup' started with ecallmgr_fs_event_stream_sup:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.867.0> exit with reason shutdown in context child_terminated
2014-08-08 09:10:57.401 [critical] <0.19312.0>@ecallmgr_fs_nodes:536 recieved node down notice for freeswitch@kazoo.viithiisys.com
2014-08-08 09:10:57.406 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_authn' started with ecallmgr_fs_authn:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.840.0> exit with reason noconnection in context child_terminated
2014-08-08 09:10:57.414 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_channel' started with ecallmgr_fs_channel:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.842.0> exit with reason noconnection in context child_terminated
2014-08-08 09:10:57.419 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_config' started with ecallmgr_fs_config:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.843.0> exit with reason noconnection in context child_terminated
2014-08-08 09:10:57.423 [error] <0.832.0> Supervisor 'freeswitch@kazoo.viithiisys.com' had child 'freeswitch@kazoo.viithiisys.com_route' started with ecallmgr_fs_route:start_link('freeswitch@kazoo.viithiisys.com', [{cookie,change_me},{client_version,<<"mod_kazoo 1.2.17-0">>}]) at <0.841.0> exit with reason noconnection in context child_terminated
2014-08-08 09:10:57.834 [error] <0.184.0> gen_server <0.184.0> terminated with reason: no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241
2014-08-08 09:10:57.837 [error] <0.184.0> CRASH REPORT Process <0.184.0> with 0 neighbours exited with reason: no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241 in gen_server:terminate/6 line 747
2014-08-08 09:10:57.838 [error] <0.178.0> Supervisor wh_couch_connection_sup had child wh_couch_connection started with wh_couch_connection:start_link({wh_couch_connection,2,"127.0.0.1",15986,[],[],false,false,true,{server,undefined,undefined,undefined,...}}) at <0.184.0> exit with reason no try clause matching {error,{conn_failed,{error,econnrefused}}} in wh_couch_connection:maybe_reconnect/1 line 241 in context child_terminated
2014-08-08 09:10:57.841 [error] <0.178.0> Supervisor wh_couch_connection_sup had child wh_couch_connection started with wh_couch_connection:start_link({wh_couch_connection,2,"127.0.0.1",15986,[],[],false,false,true,{server,undefined,undefined,undefined,...}}) at <0.184.0> exit with reason reached_max_restart_intensity in context shutdown
2014-08-08 09:10:57.841 [error] <0.171.0> Supervisor whistle_couch_sup had child wh_couch_connection_sup started with wh_couch_connection_sup:start_link() at <0.178.0> exit with reason shutdown in context child_terminated
2014-08-08 09:11:09.983 [error] <0.108.0> Connection (<0.108.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-08 09:11:10.007 [error] <0.108.0> gen_server <0.108.0> terminated with reason: socket_closed_unexpectedly
2014-08-08 09:11:10.007 [error] <0.108.0> CRASH REPORT Process <0.108.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/6 line 747
2014-08-08 09:11:10.013 [critical] <0.105.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: not_connected
2014-08-08 09:11:10.024 [error] <0.106.0> Supervisor {<0.106.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.107.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.108.0> exit with reason socket_closed_unexpectedly in context child_terminated
2014-08-08 09:11:10.027 [error] <0.106.0> Supervisor {<0.106.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.107.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.108.0> exit with reason reached_max_restart_intensity in context shutdown
2014-08-08 09:11:10.383 [error] <0.110.0> Connection (<0.110.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-08 09:11:10.424 [error] <0.110.0> gen_server <0.110.0> terminated with reason: socket_closed_unexpectedly
2014-08-08 09:11:10.425 [error] <0.110.0> CRASH REPORT Process <0.110.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:terminate/6 line 747
2014-08-08 09:11:10.437 [critical] <0.107.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: not_connected
2014-08-08 09:11:10.443 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason socket_closed_unexpectedly in context child_terminated
2014-08-08 09:11:10.447 [error] <0.108.0> Supervisor {<0.108.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.109.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"127.0.0.1",5672,0,0,0,500,none,[#Fun<amqp_uri..>,...],...}) at <0.110.0> exit with reason reached_max_restart_intensity in context shutdown
2014-08-11 23:57:59.176 [error] <0.108.0> Connection (<0.108.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-11 23:57:59.182 [critical] <0.105.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: closing
2014-08-11 23:57:59.121 [error] <0.110.0> Connection (<0.110.0>) closing: received hard error {'connection.close',320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>,0,0} from server

2014-08-11 23:57:59.128 [critical] <0.107.0>@wh_amqp_connection:00000000000:347 unable to establish command channel to amqp://guest:guest@127.0.0.1:5672, assuming connection is invalid: closing
2014-08-11 23:58:04.275 [error] <0.926.0> gen_server wh_gen_changes_system_config terminated with reason: connection_closed
2014-08-11 23:58:04.275 [error] <0.926.0> CRASH REPORT Process wh_gen_changes_system_config with 0 neighbours exited with reason: connection_closed in gen_server:terminate/6 line 747
2014-08-11 23:58:04.278 [error] <0.912.0> gen_server wh_gen_changes_offnet terminated with reason: connection_closed
2014-08-11 23:58:04.278 [error] <0.912.0> CRASH REPORT Process wh_gen_changes_offnet with 0 neighbours exited with reason: connection_closed in gen_server:terminate/6 line 747
2014-08-11 23:58:04.278 [error] <0.180.0> Supervisor wh_change_handler_sup had child wh_change_handler started with wh_change_handler:start_link({db,{server,"127.0.0.1",15984,[],[{max_sessions,512},{max_pipeline_size,10},{connect_timeout,500}]},...}, []) at <0.926.0> exit with reason connection_closed in context child_terminated
2014-08-11 23:58:04.281 [error] <0.180.0> Supervisor wh_change_handler_sup had child wh_change_handler started with wh_change_handler:start_link({db,{server,"127.0.0.1",15984,[],[{max_sessions,512},{max_pipeline_size,10},{connect_timeout,500}]},...}, []) at <0.912.0> exit with reason connection_closed in context child_terminated
